### ISSUE TITLE
`modify_ae_header()` or `modify_header()`

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#118]
Generally, I think it's a good idea that gtsummary objects have a defined structure for using statistics in headers, spanning headers, captions, and footnotes. 

Question: Do you want to wait for gtsummary to implement this functionality? We'd need to wait for another gtsummary release, unfortunately. I think we could plan for a release after the hackathon on Apr 7.

**Comment by tgerke** [comment]
Using `modify_ae_*` instead of `gtsummary::modify_*` felt odd as an end-user, I think using the defined structure would be a huge improvement. If you plan on implementing this, I would vote waiting on the gtsummary release if necessary. I imagine you'll sunset `modify_ae_*` and anyone who picks up {gtreg} between now and Apr will end up with legacy code that needs to be updated.

**Comment by ddsjoberg** [comment]
OK, sounds good! I'll track that progress in gtsummary here https://github.com/ddsjoberg/gtsummary/issues/1165

**Comment by shannonpileggi** [comment]
side chat regarding gtsummary possible updates: it is set so that if you add a column header, we automatically unhide this column for you (useful when you're merging in stats from another data frame).

In gtreg, the selectors like `all_ae_cols()` select all the columns, even the hidden. If these are used to add headers, the hidden columns (e.g. the unobserved cols that are present in every table) would be unhidden.

We'll need to update to either make `all_ae_cols()` not select hidden columns. If there would ever be a need to select the hidden columns, we could add an argument `add_ae_cols(hidden = FALSE)`
