### ISSUE TITLE
a function for regulatory printing

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/gtreg#124]
In a submission to the Food and Drug Administration for an Investigational New Drug Application , it is required to print out all serious adverse events grouped by system organ class. This sort of printing does not have any data reduction - all observed events are printed.

As an example, we can take grade 5 events from `df_adverse_events`.

``` r
library(tidyverse)
library(gtreg)

ex <- df_adverse_events %>% 
  filter(grade == 5) %>% 
  arrange(system_organ_class, adverse_event) %>% 
  select(system_organ_class, adverse_event, grade, drug_attribution, patient_id)

ex
#> # A tibble: 22 x 5
#>    system_organ_class       adverse_event      grade drug_attribution patient_id
#>    <chr>                    <chr>              <int> <fct>            <chr>     
#>  1 Blood and lymphatic sys~ Anaemia                5 Probably         ID 10     
#>  2 Blood and lymphatic sys~ Anaemia                5 Unrelated        ID 5      
#>  3 Blood and lymphatic sys~ Anaemia                5 Unrelated        ID 8      
#>  4 Blood and lymphatic sys~ Increased tendenc~     5 Unrelated        ID 1      
#>  5 Blood and lymphatic sys~ Increased tendenc~     5 Probably         ID 5      
#>  6 Blood and lymphatic sys~ Iron deficiency a~     5 Possible         ID 5      
#>  7 Blood and lymphatic sys~ Iron deficiency a~     5 Possible         ID 5      
#>  8 Blood and lymphatic sys~ Iron deficiency a~     5 Unrelated        ID 9      
#>  9 Blood and lymphatic sys~ Thrombocytopenia       5 Unrelated        ID 2      
#> 10 Blood and lymphatic sys~ Thrombocytopenia       5 Probably         ID 3      
#> # ... with 12 more rows
```

<sup>Created on 2022-03-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Where a printed deliverable might look something like:

![image](https://user-images.githubusercontent.com/17747575/159389199-a52fe9b4-3c49-4792-86e5-cec2b495ddf9.png)

* Is this a worthwhile addtion to {gtreg}?
* What to name the function?
* Could styling options be similar to labels/levels for grouped headers vs sub-header listings?
* Could output formats be compatible with various deliverables, like html, word, pdf, excel?

**Comment by ddsjoberg** [comment]
I think there are two ways to go about this:
1. We write a new function that does grouped listings. We input a data frame that is grouped by a single column (e.g. SOC), we do some manual preparation/formatting of the tibble to insert the grouped header row, and then we can convert it to a gtsummary table with a function like `bstfun::as_gtsummary()`. We could label the grouping rows internally and label or level row, so that a function like `bold_labels()` will work on the resulting table. This is the _much_ easier option to implement.
2. We could update `as_tibble()` to have a grouping option. The current grouping option is to add a new column, and we would add a second that adds a grouping row (like the default gt grouping).

I think #1 sounds like the way to go. What do you think?

**Comment by shannonpileggi** [comment]
Option 1 sounds great!

**Comment by ddsjoberg** [comment]
per our conversation, the current leading name is `tbl_listing()`
