### ISSUE TITLE
special characters not accepted in strata values

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/gtreg#174]
```
library(gtreg)
library(tidyverse)

df_ae <- df_adverse_events %>%
  mutate(
    trt2 = str_replace(trt, "Drug", "Drug\n") 
  ) 

df_pt <- df_patient_characteristics |> 
  mutate(
    trt2 = str_replace(trt, "Drug", "Drug\n") 
  )

df_ae |> 
  tbl_ae(
    id = patient_id,
    id_df = df_pt,
    ae = adverse_event,
    soc = system_organ_class,
    by = grade,
    strata = trt2
  )
```

results in 

```
Error in `dplyr::rows_update()`:
! `y` key values must be unique.
ℹ The following rows contain duplicate key values: `c(1, 2)`.
Run `rlang::last_error()` to see where the error occurred.
```

The user could achieve this through `modify_` functions. Should we issue a warning when special characters are detected?

**Comment by ddsjoberg** [comment]
Somewhere in the core where the tbls are built, `"Drug\n A"` is being converted to `"Drug\nA"`, which is causing the error we're seeing much further down stream

**Comment by ddsjoberg** [comment]
OY! The spanning headers are processed with `glue::glue()` so that we can dynamically at Ns, levels, etc. But it has a funny property removing the trailing space after `\n`!

``` r
as.character(glue::glue("Drug\n A"))
#> [1] "Drug\nA"
```

<sup>Created on 2022-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


I am not sure how to fix this on the gtsummary side. Probably, we just need to process the stratum level with glue so that they match and can be merged.
