### ISSUE TITLE
AE generic TLF shells 

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/gtreg#85]
Let's brainstorm possible methods to create a generic TLF shell.

![image](https://user-images.githubusercontent.com/17747575/151842750-19edd6ac-df3f-45c1-a92f-3131c11566d6.png)

**Comment by ddsjoberg** [comment]
This would do the trick!

```r
library(gtreg)

tbl <-
  tibble::tibble(
  soc = "System Organ Class 1",
  ae = "AE1",
  grade = factor(1, levels = 1:5)
) %>%
  {dplyr::bind_rows(., .)} %>%
  dplyr::mutate(
    id = 1:2,
    strata = c("Arm A", "Arm B")
  ) %>%
  tbl_ae(
    id = id,
    ae = ae, 
    soc = soc,
    by = grade, 
    strata = strata, 
    statistic = "xx (xx.x)",
    header_strata = "**{level} (N=xx), n (%)**",
    zero_symbol = NULL
  ) %>%
  add_overall(across = "overall-only") %>%
  modify_spanning_header(stat_1_2 = "**Overall (N=xx)**") %>%
  modify_header(stat_1_2 = "**All Grades**") %>%
  bold_labels()
```
![image](https://user-images.githubusercontent.com/26774684/151846707-b3028eb6-f841-4da7-9959-fa13422eb719.png)

**Comment by ddsjoberg** [comment]
also if we do add a gtreg theme, we could add instructions in there to left justify a caption in kable/kableExtra output

**Comment by shannonpileggi** [comment]
Oh that is awesome!  Would be a nice little vignette to add, I can put that on my documentation to-do list.

**Comment by ddsjoberg** [comment]
maybe we export a small dummy dataset with the vignette. (I mean we can just create the data set in the vignette for now, and in a future release include the dummy data set as a part of the package.

**Comment by ddsjoberg** [comment]
@shannonpileggi I started making the update to allow continuous and continuous2 variables to pass statistics like `"xxx.xx"`. It turned out to be complicated, but I think there is a better solution:

Rather than passing fake stat summaries to `tbl_summary()`, we can just create a summary table and use a shell function to replace the statistics in the body of the table with dummy stats like `"xx.x"`. I think it would look something like this:

```r
trial %>%
  tbl_summary() %>%
  create_shell()
```

We could also take advantage of the specified digits to place the correct number of Xs after the decimal point.
